### ISSUE TITLE
Update from 3.0 to 3.0.1

### ISSUE THREAD

**Issue by cedrichatem** [Hopebaytech/redmine_issue_reminder#125]
Hi,
Do you know how should I update from 3.0.0 to 3.0.1 ?
I've made a git clone and try RAILS_ENV=production rake redmine:plugins:migrate

But I get this kind of errors 
Caused by:
Mysql2::Error: Table 'reminder_roles' already exists
/var/lib/gems/2.3.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'reminder_roles' already exists: CREATE TABLE `reminder_roles` (`id` int(11) auto_increment PRIMARY KEY, `reminder_id` int(11), `role_id` int(11)) ENGINE=InnoDB
/var/lib/gems/2.3.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
/var/lib/gems/2.3.0/gems/mysql2-0.4

How could I solve that ?

Thanks and regard,

Cédric

**Comment by cedrichatem** [comment]
Hi Guys !

I solved it by renaming the different tables.
And then transfert the content to the new tables.

Cédric
