### ISSUE TITLE
Can't install this plugin from redmine2.6 branch at Redmine 2.6.3

### ISSUE THREAD

**Issue by makhomed** [Hopebaytech/redmine_issue_reminder#24]
Can't install this plugin from redmine2.6 branch at Redmine 2.6.3:

```
$ cd {REDMINE_ROOT}/plugins
$ git clone -b redmine2.6 --single-branch https://github.com/Hopebaytech/redmine_issue_reminder.git
$ bundle install
$ rake redmine:plugins:migrate
```

when I run command ```$ rake redmine:plugins:migrate``` - I got error:

```
$ rake redmine:plugins:migrate --trace
(in /home/www/redmine)
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
ActiveRecord::AdapterNotSpecified: database configuration does not specify adapter
/usr/local/share/gems/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:47:in `resolve_hash_connection'
/usr/local/share/gems/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:41:in `resolve_string_connection'
/usr/local/share/gems/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:25:in `spec'
/usr/local/share/gems/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:130:in `establish_connection'
/usr/local/share/gems/gems/activerecord-3.2.21/lib/active_record/railtie.rb:88:in `block (2 levels) in <class:Railtie>'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:26:in `block in on_load'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:25:in `each'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:25:in `on_load'
/usr/local/share/gems/gems/activerecord-3.2.21/lib/active_record/railtie.rb:80:in `block in <class:Railtie>'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `each'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/www/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/application.rb:103:in `require_environment!'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/share/ruby/monitor.rb:211:in `mon_synchronize'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/share/ruby/monitor.rb:211:in `mon_synchronize'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/local/share/gems/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
```

How I can install this plugin from redmine2.6 branch at Redmine 2.6.3 ?

```
OS: CentOS 7.1, system ruby.

Environment:
  Redmine version                2.6.3.stable
  Ruby version                   2.0.0-p598 (2014-11-13) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
```

**Comment by Androc** [comment]
Hello,

The README does not precize it but you must append RAILS_ENV="production"
to your command line if it is not set in your shell

**Comment by makhomed** [comment]
> The README does not precize it but you must append RAILS_ENV="production"
> to your command line if it is not set in your shell

I am also tried such variant - and it is not work too:

```
$ rake redmine:plugins:migrate RAILS_ENV=production --trace
(in /home/www/redmine)
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
LoadError: cannot load such file -- minitest/unit
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/share/ruby/test/unit/assertions.rb:1:in `<top (required)>'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/share/ruby/test/unit/testcase.rb:1:in `<top (required)>'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/test_case.rb:1:in `<top (required)>'
/usr/local/share/gems/gems/actionpack-3.2.21/lib/action_controller/test_case.rb:355:in `<module:ActionController>'
/usr/local/share/gems/gems/actionpack-3.2.21/lib/action_controller/test_case.rb:7:in `<top (required)>'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/actionpack-3.2.21/lib/action_view/test_case.rb:5:in `<top (required)>'
/usr/local/share/gems/gems/prototype-rails-3.2.1/lib/prototype-rails/on_load_action_view.rb:17:in `<top (required)>'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/prototype-rails-3.2.1/lib/prototype-rails.rb:12:in `block (2 levels) in <class:Engine>'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:26:in `block in on_load'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:25:in `each'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:25:in `on_load'
/usr/local/share/gems/gems/prototype-rails-3.2.1/lib/prototype-rails.rb:11:in `block in <class:Engine>'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `each'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/www/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/application.rb:103:in `require_environment!'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/share/ruby/monitor.rb:211:in `mon_synchronize'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/share/ruby/monitor.rb:211:in `mon_synchronize'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/local/share/gems/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
```

**Comment by Androc** [comment]
Try bundle update and rake migrate from your redmine directory, not the
plugin directory

**Comment by makhomed** [comment]
> Try bundle update and rake migrate from your redmine directory, not the plugin directory

still got error ```LoadError: cannot load such file -- minitest/unit```:

```
# cd /home/www/redmine
# bundle update
# su - www
$ cd /home/www/redmine
$ rake redmine:plugins:migrate RAILS_ENV=production
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
rake aborted!
LoadError: cannot load such file -- minitest/unit
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/test_case.rb:1:in `<top (required)>'
/usr/local/share/gems/gems/actionpack-3.2.21/lib/action_controller/test_case.rb:355:in `<module:ActionController>'
/usr/local/share/gems/gems/actionpack-3.2.21/lib/action_controller/test_case.rb:7:in `<top (required)>'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/actionpack-3.2.21/lib/action_view/test_case.rb:5:in `<top (required)>'
/usr/local/share/gems/gems/prototype-rails-3.2.1/lib/prototype-rails/on_load_action_view.rb:17:in `<top (required)>'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/prototype-rails-3.2.1/lib/prototype-rails.rb:12:in `block (2 levels) in <class:Engine>'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:26:in `block in on_load'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:25:in `each'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:25:in `on_load'
/usr/local/share/gems/gems/prototype-rails-3.2.1/lib/prototype-rails.rb:11:in `block in <class:Engine>'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `each'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/www/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/application.rb:103:in `require_environment!'
/usr/local/share/gems/gems/railties-3.2.21/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by Androc** [comment]
Your problem seems more general than just about Issue Reminder.
It is about the minitest gem which should be installed by default with ActiveSupport.

Try to add `gem 'minitest'` in your Gemfile and run `bundle update`.
It should solve your issue.

**Comment by makhomed** [comment]
> Your problem seems more general than just about Issue Reminder.
> It is about the minitest gem which should be installed by default with ActiveSupport.

I use Redmine 2.6.3, and Redmine 2.6.3 uses Rails 3.2, and Rails 3.2 uses ActiveSupport 3.2.21.

ActiveSupport 3.2.21 does not require minitest, I grep all files inside
/usr/local/share/gems/gems/activesupport-3.2.21 - no string 'minitest' found at all.

You are talking about Redmine 3.0.x, which uses Rails 4.2 - that ActiveSupport uses minitest:
```
$ cat /usr/local/share/gems/gems/activesupport-4.2.1/lib/active_support/testing/autorun.rb
gem 'minitest'

require 'minitest'

Minitest.autorun
```

> Try to add gem 'minitest' in your Gemfile and run bundle update.
> It should solve your issue.

```
$ diff -u redmine_issue_reminder/Gemfile.old redmine_issue_reminder/Gemfile
--- redmine_issue_reminder/Gemfile.old  2015-04-10 15:57:40.843329763 +0300
+++ redmine_issue_reminder/Gemfile      2015-04-10 15:56:45.990403063 +0300
@@ -1,5 +1,6 @@
 # For redmine_issue_reminder
 gem "prototype-rails"
+gem "minitest"

 # Inline CSS
 gem 'premailer-rails'
```

Yes, this suggested by you patch help, and plugin ```Redmine Issue Reminder```
branch redmine2.6 installs normally into Redmine 2.6.3, thank you!

> Edit : I have the same configuration as yours and I don't have the minitest gem installed.

Not the same.  In Gemfile from master branch you can found 
```gem 'prototype-rails', github: 'rails/prototype-rails', branch: '4.2'```
in Gemfile from redmine2.6 branch: ```gem "prototype-rails"```
probably newer version of prototype-rails or activesupport gems
will load  minitest gem automatically for Redmine 3.x and Rails 4.2.

**Comment by Androc** [comment]
I only read your error message :
```
LoadError: cannot load such file -- minitest/unit
/usr/local/share/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
```
That is why I assumed your ActiveSupported needed minitest.

Glad your problem is solved :)

**Comment by makhomed** [comment]
I fixed this issue with ```redmine2.6``` branch by patch:

```
$ diff -u redmine_issue_reminder/Gemfile.old redmine_issue_reminder/Gemfile
--- redmine_issue_reminder/Gemfile.old  2015-04-10 15:57:40.843329763 +0300
+++ redmine_issue_reminder/Gemfile      2015-04-10 15:56:45.990403063 +0300
@@ -1,5 +1,6 @@
 # For redmine_issue_reminder
 gem "prototype-rails"
+gem "minitest"

 # Inline CSS
 gem 'premailer-rails'
```

but probably this patch should be merged into redmine2.6 branch,
because many people still use Redmine 2.6.x and can't upgrade Redmine to 3.x version.

**Comment by Androc** [comment]
It is strange because I also use redmine 2.6 and does not have the same problem.
The problem needs to be identified more clearly but at least there is a solution.
